namespace Booking.Ticketing.Dto
{
    public class TicketDocument
    {
        public string Aw_deep_link { get; set; }
        public string Product_name { get; set; }
        public string Aw_product_id { get; set; }
        public string Merchant_product_id { get; set; }
        public string Merchant_image_url { get; set; }
        public string Description { get; set; }
        public string Merchant_category { get; set; }
        public string Search_price { get; set; }
        public string Merchant_name { get; set; }
        public string Merchant_id { get; set; }
        public string Category_name { get; set; }
        public string Category_id { get; set; }
        public string Aw_image_url { get; set; }
        public string Currency { get; set; }
        public string Store_price { get; set; }
        public string Delivery_cost { get; set; }
        public string Merchant_deep_link { get; set; }
        public string Language { get; set; }
        public string Last_updated { get; set; }
        public string Display_price { get; set; }
        public string Data_feed_id { get; set; }
        public string Brand_name { get; set; }
        public string Brand_id { get; set; }
        public string Colour { get; set; }
        public string Product_short_description { get; set; }
        public string Specifications { get; set; }
        public string Condition { get; set; }
        public string Product_model { get; set; }
        public string Model_number { get; set; }
        public string Dimensions { get; set; }
        public string Keywords { get; set; }
        public string Promotional_text { get; set; }
        public string Product_type { get; set; }
        public string Commission_group { get; set; }
        public string Merchant_product_category_path { get; set; }
        public string Merchant_product_second_category { get; set; }
        public string Merchant_product_third_category { get; set; }
        public string Rrp_price { get; set; }
        public string Saving { get; set; }
        public string Savings_percent { get; set; }
        public string Base_price { get; set; }
        public string Base_price_amount { get; set; }
        public string Base_price_text { get; set; }
        public string Product_price_old { get; set; }
        public string Delivery_restrictions { get; set; }
        public string Delivery_weight { get; set; }
        public string Warranty { get; set; }
        public string Terms_of_contract { get; set; }
        public string Delivery_time { get; set; }
        public string In_stock { get; set; }
        public string Stock_quantity { get; set; }
        public string Valid_from { get; set; }
        public string Valid_to { get; set; }
        public string Is_for_sale { get; set; }
        public string Web_offer { get; set; }
        public string Pre_order { get; set; }
        public string Stock_status { get; set; }
        public string Size_stock_status { get; set; }
        public string Size_stock_amount { get; set; }
        public string Merchant_thumb_url { get; set; }
        public string Large_image { get; set; }
        public string Alternate_image { get; set; }
        public string Aw_thumb_url { get; set; }
        public string Alternate_image_two { get; set; }
        public string Alternate_image_three { get; set; }
        public string Alternate_image_four { get; set; }
        public string Reviews { get; set; }
        public string Average_rating { get; set; }
        public string Rating { get; set; }
        public string Number_available { get; set; }
        public string Custom_1 { get; set; }
        public string Custom_2 { get; set; }
        public string Custom_3 { get; set; }
        public string Custom_4 { get; set; }
        public string Custom_5 { get; set; }
        public string Custom_6 { get; set; }
        public string Custom_7 { get; set; }
        public string Custom_8 { get; set; }
        public string Custom_9 { get; set; }
        public string Ean { get; set; }
        public string Isbn { get; set; }
        public string Upc { get; set; }
        public string Mpn { get; set; }
        public string Parent_product_id { get; set; }
        public string Product_GTIN { get; set; }
        public string Basket_link { get; set; }
        public string Tickets_primary_artist { get; set; }
        public string Tickets_second_artist { get; set; }
        public string Tickets_event_date { get; set; }
        public string Tickets_event_name { get; set; }
        public string Tickets_venue_name { get; set; }
        public string Tickets_venue_address { get; set; }
        public string Tickets_available_from { get; set; }
        public string Tickets_genre { get; set; }
        public string Tickets_min_price { get; set; }
        public string Tickets_max_price { get; set; }
        public string Tickets_longitude { get; set; }
        public string Tickets_latitude { get; set; }
        public string Tickets_event_location_address { get; set; }
        public string Tickets_event_location_zipcode { get; set; }
        public string Tickets_event_location_city { get; set; }
        public string Tickets_event_location_region { get; set; }
        public string Tickets_event_location_country { get; set; }
        public string Tickets_event_location_coordinates { get; set; }
        public string Tickets_event_duration { get; set; }

    }
}
